import type { NextPage } from "next";
import Head from "next/head";
import ThemeToggle from "../components/ThemeToggle/ThemeToggle";

const Home: NextPage = () => {

  return (
    <div className="absolute top-0 bottom-0 left-0 right-0">
      <Head>
        <title>SchemeSonic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ThemeToggle/>
        Hello world!
      </div>
    </div>
  );
};

export default Home;
